gooddays

diff --git a/.github/workflows/tyledecloud.yml b/.github/workflows/tyledecloud.yml
--- a/.github/workflows/tyledecloud.yml
+++ b/.github/workflows/tyledecloud.yml
@@ -1,39 +1,44 @@
-name: Deploy Node.js App to DigitalOcean
+name: CI/CD Pipeline for DigitalOcean
 
 on:
   push:
     branches:
-      - tyledecloud-server  # Change to your branch name
+      - tyledecloud-server  # Trigger on pushes to the specified branch
 
 jobs:
   build:
+    name: Build tyldecloudserver_app
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v3
+    - name: Check out code
+      uses: actions/checkout@v3
 
-      - name: Login to DigitalOcean Container Registry
-        uses: docker/login-action@v3
-        with:
-          registry: registry.digitalocean.com
-          username: oauth2
-          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
+    - name: Login to DigitalOcean Container Registry
+      uses: docker/login-action@v3
+      with:
+        registry: registry.digitalocean.com
+        username: oauth2
+        password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
 
-      - name: Build, Tag, and Push Image
-        env:
-          DOCR_REGISTRY: registry.digitalocean.com/cloudy001
-          REPOSITORY: tyldecloudserver_app
-        run: |
-          docker build -t $DOCR_REGISTRY/$REPOSITORY:${GITHUB_RUN_NUMBER} .
-          docker push $DOCR_REGISTRY/$REPOSITORY:${GITHUB_RUN_NUMBER}
+    - name: Build, tag, and push image to DOCR
+      id: build-and-push
+      env:
+        DOCR_REGISTRY: registry.digitalocean.com/cloudy001
+        REPOSITORY: tyldecloudserver_app
+      run: |
+        echo "$DOCR_REGISTRY/$REPOSITORY:${GITHUB_RUN_NUMBER}"
+        docker build -t $DOCR_REGISTRY/$REPOSITORY:${GITHUB_RUN_NUMBER} .
+        docker push $DOCR_REGISTRY/$REPOSITORY:${GITHUB_RUN_NUMBER}
+        echo "$DOCR_REGISTRY" > docr_registry.txt
 
-      - name: Upload DOCR Registry Info
-        uses: actions/upload-artifact@v3
-        with:
-          name: docr-registry
-          path: docr_registry.txt
+    - name: Upload DOCR Registry
+      uses: actions/upload-artifact@v3
+      with:
+        name: docr-registry
+        path: docr_registry.txt
 
   deploy:
+    name: Deploy tyldecloudserver to dev
     runs-on: ubuntu-latest
     needs: build
     env:
@@ -42,47 +47,66 @@ jobs:
       COMPOSE: compose.yml
 
     steps:
-      - name: Download DOCR Registry
-        uses: actions/download-artifact@v3
-        with:
-          name: docr-registry
-          path: .
+    - name: Download DOCR Registry
+      uses: actions/download-artifact@v3
+      with:
+        name: docr-registry
+        path: .
 
-      - name: Read DOCR Registry
-        run: |
-          DOCR_REGISTRY=$(cat docr_registry.txt)
-          echo "DOCR_REGISTRY=$DOCR_REGISTRY" >> $GITHUB_ENV
+    - name: Read DOCR Registry
+      run: |
+        DOCR_REGISTRY=$(cat docr_registry.txt)
+        echo "DOCR_REGISTRY=$DOCR_REGISTRY" >> $GITHUB_ENV
+    
+    
+    - name: Setup SSH Key
+      run: |
+        echo "${{ secrets.DROPLET_SSH_KEY }}" | tr -d '\r' > private_key.pem
+        chmod 600 private_key.pem
 
-      - name: Setup SSH Key
-        run: |
-          echo "${{ secrets.DROPLET_SSH_KEY }}" | tr -d '\r' > private_key.pem
-          chmod 600 private_key.pem
+    - name: Test SSH Connection
+      run: |
+        ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} "echo 'SSH Connection Successful'"
 
-      - name: Test SSH Connection
-        run: |
-          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} "echo 'SSH Connection Successful'"
+    - name: Transfer SSL Certificate to DigitalOcean Droplet
+      run: |
+        echo "${{ secrets.SSL_CERTIFICATE }}" | ssh -o StrictHostKeyChecking=no -i private_key.pem \
+        ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} "cat > /etc/ssl/certs/cert.pem"
 
-      - name: Transfer SSL Certificate to DigitalOcean Droplet
-        run: |
-          echo "${{ secrets.SSL_CERTIFICATE }}" | ssh -o StrictHostKeyChecking=no -i private_key.pem \
-          ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} "cat > /etc/ssl/certs/cert.pem"
+        echo "${{ secrets.SSL_KEY }}" | ssh -o StrictHostKeyChecking=no -i private_key.pem \
+        ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} "cat > /etc/ssl/private/key.pem"
 
-          echo "${{ secrets.SSL_KEY }}" | ssh -o StrictHostKeyChecking=no -i private_key.pem \
-          ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} "cat > /etc/ssl/private/key.pem"
+        ssh -o StrictHostKeyChecking=no -i private_key.pem \
+        ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} "chmod 600 /etc/ssl/certs/cert.pem && chmod 600 /etc/ssl/private/key.pem"
 
-          ssh -o StrictHostKeyChecking=no -i private_key.pem \
-          ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} "chmod 600 /etc/ssl/certs/cert.pem && chmod 600 /etc/ssl/private/key.pem"
+    - name: SSH Login to DigitalOcean Droplet
+      uses: appleboy/ssh-action@v1.0.3
+      with:
+        host: ${{ secrets.DROPLET_IP }}
+        username: ${{ secrets.DROPLET_USER }}
+        key: ${{ secrets.DROPLET_SSH_KEY }}
+        port: ${{ secrets.PORT }}
+        envs: GITHUB_TRIGGERING_ACTOR,GITHUB_RUN_NUMBER,DOCR_REGISTRY,REPOSITORY,DIRECTORY,COMPOSE
+        script: |
+          echo "Environment Variables:"
+          echo "GITHUB_TRIGGERING_ACTOR: $GITHUB_TRIGGERING_ACTOR"
+          echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
+          echo "DOCR_REGISTRY: $DOCR_REGISTRY"
+          echo "REPOSITORY: $REPOSITORY"
+          echo "DIRECTORY: $DIRECTORY"
+          echo "COMPOSE: $COMPOSE"
+          echo "$GITHUB_TRIGGERING_ACTOR - Deployment Initiated - \nPulling build artifact $DOCR_REGISTRY/$REPOSITORY:${GITHUB_RUN_NUMBER}"
+  
+          # Updating the image in docker-compose.yaml using yq (correct syntax for yq)
+          cd $DIRECTORY && yq eval '.services.web.image = "${DOCR_REGISTRY}/${REPOSITORY}:${GITHUB_RUN_NUMBER}"' -i $COMPOSE && \
+  
+          # Running Docker Compose to build and recreate the services
+          docker compose up --build --force-recreate -d
 
-      - name: Deploy Application
-        uses: appleboy/ssh-action@v1.0.3
-        with:
-          host: ${{ secrets.DROPLET_IP }}
-          username: ${{ secrets.DROPLET_USER }}
-          key: ${{ secrets.DROPLET_SSH_KEY }}
-          script: |
-            cd $DIRECTORY
-            echo "Updating Docker Compose file..."
-            yq eval '.services.web.image = "${DOCR_REGISTRY}/${REPOSITORY}:${GITHUB_RUN_NUMBER}"' -i $COMPOSE
-            echo "Recreating Services..."
-            docker compose up --build --force-recreate -d
-            echo "Deployment Successful!"
+          # Checking the exit status to determine if the deployment was successful
+          if [[ $? == 0 ]]; then
+            echo "Deployment Successful!!!"
+          else
+            echo "Error!!!!! Can not recreate service update"
+            exit 1
+          fi
